<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class GeminiService
{
    protected $apiKey;
        protected $url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent";

            public function __construct()
                {
                        $this->apiKey = env('GEMINI_API_KEY');
                            }

                                public function analyze($data)
                                    {
                                            // الميثاق القانوني والأخلاقي الصارم (Prompt Engineering)
                                                    $systemCharter = "
                                                            أنت خبير خدمة عملاء ومسوق محترف لمنشأة سعودية (نوع المنشأة: {$data['type']}).
                                                                    مهمتك: تحليل التعليق والرد عليه بناءً على الميثاق التالي:
                                                                            1. [الأمان القانوني]: ممنوع منعاً باتاً تقديم استشارات طبية، قانونية، أو مالية. الرد: 'نعتذر، لا يمكننا التعليق على هذا الجانب، ونسعد بتواصلكم عبر القنوات الرسمية'.
                                                                                    2. [الابتزاز والإساءة]: لا تعتذر للمبتز أو المسيء، رد بمهنية: 'نحرص على جودة خدمتنا، ويسعدنا استقبال ملاحظاتكم عبر القنوات الرسمية'.
                                                                                            3. [البيانات الحساسة]: إذا وجد رقم هاتف أو اسم موظف، ضع sensitive_flag = true ولا تذكرها في الرد.
                                                                                                    4. [الأسلوب]: رد بشري فريد، غير مكرر، من 1-3 جمل فقط.
                                                                                                            5. [حجم المنشأة]: مستوى الحساسية (Tier) هو {$data['tier']}/2.0. كلما زاد التير، زادت الرسمية والحذر.
                                                                                                                    ";

                                                                                                                            $prompt = "
                                                                                                                                    اسم المنشأة: {$data['name']}
                                                                                                                                            نص التعليق: \"{$data['text']}\"
                                                                                                                                                    عدد النجوم: {$data['stars']}
                                                                                                                                                            
                                                                                                                                                                    أجب بصيغة JSON فقط كالتالي:
                                                                                                                                                                            {
                                                                                                                                                                                      \"sentiment\": \"إيجابي أو سلبي أو محايد\",
                                                                                                                                                                                                \"category\": \"شكوى أو ابتزاز أو مطالبة أو عام\",
                                                                                                                                                                                                          \"reply\": \"نص الرد هنا\",
                                                                                                                                                                                                                    \"sensitive_flag\": true/false
                                                                                                                                                                                                                            }";

                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                $response = Http::post($this->url . "?key=" . $this->apiKey, [
                                                                                                                                                                                                                                                                "contents" => [
                                                                                                                                                                                                                                                                                    ["parts" => [["text" => $systemCharter . "\n" . $prompt]]]
                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                    "generationConfig" => [
                                                                                                                                                                                                                                                                                                                                        "response_mime_type" => "application/json"
                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                    ]);

                                                                                                                                                                                                                                                                                                                                                                                $result = $response->json();
                                                                                                                                                                                                                                                                                                                                                                                            $jsonContent = $result['candidates'][0]['content']['parts'][0]['text'];
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                    return json_decode($jsonContent, true);

                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (\Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        Log::error("Gemini API Error: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'sentiment' => 'غير مصنف',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'category' => 'خطأ فني',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'reply' => 'نعتذر، واجهنا مشكلة في تحليل التعليق حالياً.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'sensitive_flag' => false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }