<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Branch;
use App\Models\Comment;
use App\Services\GeminiService;
use App\Services\PricingEngine;

class ReputationController extends Controller
{
    protected $gemini;
        protected $pricing;

            /**
                 * حقن الخدمات (Gemini و محرك التسعير) داخل المتحكم
                      */
                          public function __construct(GeminiService $gemini, PricingEngine $pricing)
                              {
                                      $this->gemini = $gemini;
                                              $this->pricing = $pricing;
                                                  }

                                                      /**
                                                           * عرض الصفحة الرئيسية (الخريطة واللوحة الجانبية)
                                                                */
                                                                    public function index()
                                                                        {
                                                                                return view('dashboard');
                                                                                    }

                                                                                        /**
                                                                                             * معالجة التعليق: التحليل، التصنيف، وتوليد الرد الآمن
                                                                                                  */
                                                                                                      public function process(Request $request)
                                                                                                          {
                                                                                                                  // 1. حساب الـ Tier (التصنيف التلقائي) للمنشأة بناءً على نوع النشاط
                                                                                                                          $tier = $this->pricing->calculateTier(
                                                                                                                                      $request->business_type, 
                                                                                                                                                  $request->total_reviews ?? 0
                                                                                                                                                          );

                                                                                                                                                                  // 2. تسجيل أو تحديث بيانات الفرع في قاعدة البيانات
                                                                                                                                                                          $branch = Branch::updateOrCreate(
                                                                                                                                                                                      ['place_id' => $request->place_id],
                                                                                                                                                                                                  [
                                                                                                                                                                                                                  'name' => $request->business_name,
                                                                                                                                                                                                                                  'business_type' => $request->business_type,
                                                                                                                                                                                                                                                  'auto_tier' => $tier,
                                                                                                                                                                                                                                                                  'knowledge_base' => $request->knowledge_base ?? 'الدوام متاح حسب جوجل، يرجى التواصل للمزيد.'
                                                                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                              // 3. إرسال التعليق لـ Gemini لتحليله بناءً على "الميثاق القانوني"
                                                                                                                                                                                                                                                                                                      $analysis = $this->gemini->analyze([
                                                                                                                                                                                                                                                                                                                  'tier' => $branch->auto_tier,
                                                                                                                                                                                                                                                                                                                              'name' => $branch->name,
                                                                                                                                                                                                                                                                                                                                          'type' => $branch->business_type,
                                                                                                                                                                                                                                                                                                                                                      'text' => $request->review_text,
                                                                                                                                                                                                                                                                                                                                                                  'stars' => $request->review_stars,
                                                                                                                                                                                                                                                                                                                                                                              'knowledge_base' => $branch->knowledge_base
                                                                                                                                                                                                                                                                                                                                                                                      ]);

                                                                                                                                                                                                                                                                                                                                                                                              // 4. حفظ التعليق والرد الناتج في قاعدة البيانات
                                                                                                                                                                                                                                                                                                                                                                                                      $comment = Comment::create([
                                                                                                                                                                                                                                                                                                                                                                                                                  'branch_id' => $branch->id,
                                                                                                                                                                                                                                                                                                                                                                                                                              'author_name' => $request->author_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                          'comment_text' => $request->review_text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      'sentiment' => $analysis['sentiment'] ?? 'غير مصنف',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'category' => $analysis['category'] ?? 'عام',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'ai_response' => $analysis['reply'] ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'sensitive_flag' => $analysis['sensitive_flag'] ?? false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 5. إعادة النتيجة للواجهة الأمامية (JavaScript)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return response()->json($comment);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * حساب باقات الاشتراك المقترحة للمنشأة (التسعير الديناميكي)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function calculatePrice(Request $request)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $type = $request->business_type;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $totalReviews = $request->total_reviews;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // السعر الأساسي المقترح لباقة البداية
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $baseStarter = 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // جلب معامل الضرب بناءً على النشاط (مثلاً المستشفى 1.7)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $tierMultiplier = $this->pricing->calculateTier($type, $totalReviews);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // حساب الأسعار النهائية للباقات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $starterPrice = round($baseStarter * $tierMultiplier);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $proPrice = round(($baseStarter + 150) * $tierMultiplier); // باقة البرو تزيد 150 ريال أساسية

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return response()->json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'starter' => $starterPrice,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'pro' => $proPrice,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'tier' => $tierMultiplier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }